class CommandEnum():
    UNKNOWN = 0
    RELEASE_ALL_SERVOS = 1
    GET_UNIQUE_ID = 2
    EZB3 = 3
    EZB4 = 4
    audio_BEEP = 5
    SERVO = 6
    I2C_WRITE = 10
    I2C_READ = 11
    BOOT_LOADER = 14
    SET_PWM_D0 = 15
    SET_SERVO_SPEED_D0 = 39
    PING = 85
    SET_DIGITAL_PORT_ON_D0 = 100
    SET_DIGITAL_PORT_OFF_D0 = 124
    GET_DIGITAL_PORT_D0 = 148
    SET_SERVO_POSITION_D0 = 172
    GET_ADC_VALUE_A0 = 196
    SEND_SERIAL_D0 = 204
    READ_HCSR04_D0 = 228
    GET_FIRMWARE_ID = 253
    SOUND_STREAM_CMD = 254

class CommandV4Enum():
    SET_LIPO_BATTERY_PROTECTION_STATE = 0
    SET_BATTERY_MONITOR_VOLTAGE = 1
    GET_BATTERY_VOLTAGE = 2
    GET_CPU_TEMPERATURE = 3
    SET_AX12_SERVO = 4
    UART0_INIT = 5
    UART0_WRITE = 6
    UART0_AVAILABLE_BYTES = 7
    UART0_READ = 8
    UART1_INIT = 9 
    UART1_WRITE = 10 
    UART1_AVAILABLE_BYTES = 11 
    UART1_READ = 12
    UART2_INIT = 13
    UART2_WRITE = 14
    UART2_AVAILABLE_BYTES = 15
    UART2_READ = 16
    SET_I2C_CLOCKSPEED = 17
    SET_UART_CLOCKSPEED = 18
    RESET_TO_DEFAULTS = 19

class CommandSoundV4Enum:
    INIT_STOP = 0
    LOAD = 1
    PLAY = 2

